version: "3.9"
services:
  shorter:
    image: ghcr.io/cupkappu/shorter:latest
    ports:
      - "3000:3000"
    environment:
      - AUTH_KEY=${AUTH_KEY:-change-me}
    volumes:
      - ./data:/app/data
    restart: unless-stopped
